### ISSUE TITLE
Management command output formats

### ISSUE THREAD

**Issue by jayvdb** [lyst/django-urlconf-export#1]
It would be nice to have a table output format which is suitable for reading on the CLI.

https://github.com/kezabelle/django-unfurl provides a text based format, but doesnt have whitelist/blacklist or JSON format.

**Comment by i18n-tribe** [comment]
Thanks for reaching out @jayvdb ! I'd be interested to understand in more detail – how would this be useful to you?

**Comment by jayvdb** [comment]
I like to be able to run a management command to list some/all of the urls, to read it, either to check it (no surprise new incorrectly secured views after an app upgrade), or to find a view that I know exists, but forgot how to get to it, or its params.

**Comment by i18n-tribe** [comment]
@jayvdb the use case you have described is a little different to the main use case for this library.  It sounds like the use-case for [django-unfurl](https://github.com/kezabelle/django-unfurl). 

This library is not designed to produce human readable url information. The goal is to enable other services to generate URLs for a Django website – e.g. if you have an email service, and you send emails that includes links to your website.

So I would not like to develop this feature myself. 

But I'd be willing to accept a PR if you'd like to implement it yourself. 

Is all the information you require available in the JSON datastructure? 

If so, implementing this feature will be easy, and can be done without disturbing other features. 

Note how [included urls](https://github.com/lyst/django-urlconf-export#included-urls) and [i18n urls](https://github.com/lyst/django-urlconf-export#i18n-urls) are represented. 

Please let me know if you would be able to work with the existing JSON data structure.

If you'd like to go forwards, I would be happy to share some suggestions about how best to implement the feature.

I've thought of an approach that is easy to implement, and will fit in well with the rest of the library.

Before I write up the proposed approach, I'd like to check if rendering the existing JSON datastructure would work for your use case.

**Comment by jayvdb** [comment]
Part of the reason for proposing it here is that I use this library for its intended purpose, and the existing JSON is good enough, but occasionally I want to read it and that hurts.  Seems like about once a week.  The filtering of this command is really helpful because I usually remember a significant part of the path.  I will just add django-unfurl for now(and propose they add filtering), as I can not promise to work on this feature myself (drowning in other OSS and bill-paying work), but I would like to hear your suggested approach.

**Comment by jayvdb** [comment]
I found that https://django-extensions.readthedocs.io/en/latest/command_extensions.html has a "show_urls", which does have json and console formats, but it also doesnt have path filtering.

**Comment by Data-Meister** [comment]
Sorry for the slow response. I’m tied up right now, but will come back to
you soon when I have a bit of free bandwidth.

**Comment by i18n-tribe** [comment]
Sorry for the slow response. I’m tied up right now, but will come back to
you soon when I have a bit of free bandwidth.

**Comment by i18n-tribe** [comment]
@jayvdb made a new issue for this https://github.com/lyst/django-urlconf-export/issues/6
